apiVersion: v1
kind: Service
metadata:
  labels:
    name: smartgrid-lessee
  name: smartgrid-lessee
  namespace: gridvo
spec:
  selector: 
    name: smartgrid-lessee
  ports:
     - port: 80
       targetPort: 3001
