apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: smartgrid-lessee
  name: smartgrid-lessee
  namespace: gridvo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: smartgrid-lessee
    spec:
      containers:
      - name: smartgrid-lessee
        image: 10.0.3.31:5000/gridvo/smartgrid-lessee:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: ZK_TRACER_HTTP
          value: "true"
        - name: IS_DEBUG
          value: "true"
             
