apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: smartgrid-lessee
  name: smartgrid-lessee
  namespace: gridvo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: smartgrid-lessee
    spec:
      containers:
      - name: smartgrid-lessee
        image: 10.0.3.31:5000/gridvo/smartgrid-lessee:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: ZK_TRACER_HTTP
          value: "true"
        - name: IS_DEBUG
          value: "true"
        - name: ZOOKEEPER_SERVICE_HOST
          value: "zookeeper"
        - name: ZOOKEEPER_SERVICE_PORT
          value: "2181"
        - name: GRIDVO_WECHAT_SERVICE_HOST
          value: "gridvo-wechat"
        - name: GRIDVO_WECHAT_SERVICE_PORT
          value: "80"
        - name: ZIPKIN_SERVICE_HOST
          value: "zipkin"
        - name: ZIPKIN_HTTP_TRANSPORT_PORT
          value: "9411"
        - name: MONGODB_SERVICE_HOST
          value: "mongodb"
        - name: MONGODB_SERVICE_PORT
          value: "27017"
             
